// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.PreSeason2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.BuiltInAccelerometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the amount of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid pneumaticsBackSolenoid;
    public static DoubleSolenoid pneumaticsFrontSolenoid;
    public static DoubleSolenoid pneumaticsBackSecondSolenoid;
    public static CANTalon drivetrainFrontLeft;
    public static CANTalon drivetrainBackLeft;
    public static CANTalon drivetrainFrontRight;
    public static CANTalon drivetrainBackRight;
    public static RobotDrive drivetrainRobotDrive;
    public static ADXRS450_Gyro roboRioMainGyro; //not from Robot Builder. A pain to type, but very accurate and useful gyro (once calibrated).
    public static PowerDistributionPanel roboRioPowerDistributionPanel; //useful in "dumb" controllers to standardize motor movement.
    public static BuiltInAccelerometer roboRioAccelerometer; //Not from Robot Builder. A specific, built-in accelerometer.
    public static DigitalInput roboRioFrontFlagSwitch;
    public static DigitalInput roboRioBackFlagSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticsBackSolenoid = new DoubleSolenoid(4, 0, 1);
        
        LiveWindow.addActuator("Pneumatics", "BottomSolenoid", pneumaticsBackSolenoid);
        
        pneumaticsFrontSolenoid = new DoubleSolenoid(4, 2, 3);
        LiveWindow.addActuator("Pneumatics", "UpperSolenoid", pneumaticsFrontSolenoid);
        
        pneumaticsBackSecondSolenoid = new DoubleSolenoid(4,4,5);
        LiveWindow.addActuator("Pneumatics", "SecondBackSolenoid", pneumaticsBackSecondSolenoid);
        
        drivetrainFrontLeft = new CANTalon(10);
        LiveWindow.addActuator("Drivetrain", "FrontLeft", drivetrainFrontLeft);
        
        drivetrainBackLeft = new CANTalon(6);
        LiveWindow.addActuator("Drivetrain", "BackLeft", drivetrainBackLeft);
        
        drivetrainFrontRight = new CANTalon(9);
        LiveWindow.addActuator("Drivetrain", "FrontRight", drivetrainFrontRight);
        
        drivetrainBackRight = new CANTalon(7);
        LiveWindow.addActuator("Drivetrain", "BackRight", drivetrainBackRight);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainFrontLeft, drivetrainBackLeft,
              drivetrainFrontRight, drivetrainBackRight);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);

        roboRioMainGyro = new ADXRS450_Gyro();
        LiveWindow.addSensor("RoboRio", "MainGyro", roboRioMainGyro);
        
        roboRioAccelerometer = new BuiltInAccelerometer();
        
        roboRioPowerDistributionPanel = new PowerDistributionPanel(3);
        LiveWindow.addSensor("RoboRio", "PowerDistributionPanel", roboRioPowerDistributionPanel);
        
        roboRioFrontFlagSwitch = new DigitalInput(7);
        roboRioBackFlagSwitch = new DigitalInput(3);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
