// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.PreSeason2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid pneumaticsBackSolenoid;
    public static DoubleSolenoid pneumaticsFrontSolenoid;
    public static CANTalon drivetrainFrontLeft;
    public static CANTalon drivetrainBackLeft;
    public static CANTalon drivetrainFrontRight;
    public static CANTalon drivetrainBackRight;
    public static RobotDrive drivetrainRobotDrive;
    public static AnalogGyro roboRioMainGyro;
    public static PowerDistributionPanel roboRioPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticsBackSolenoid = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Pneumatics", "BottomSolenoid", pneumaticsBackSolenoid);
        
        pneumaticsFrontSolenoid = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Pneumatics", "UpperSolenoid", pneumaticsFrontSolenoid);
        
        drivetrainFrontLeft = new CANTalon(10);
        LiveWindow.addActuator("Drivetrain", "FrontLeft", drivetrainFrontLeft);
        
        drivetrainBackLeft = new CANTalon(12);
        LiveWindow.addActuator("Drivetrain", "BackLeft", drivetrainBackLeft);
        
        drivetrainFrontRight = new CANTalon(11);
        LiveWindow.addActuator("Drivetrain", "FrontRight", drivetrainFrontRight);
        
        drivetrainBackRight = new CANTalon(13);
        LiveWindow.addActuator("Drivetrain", "BackRight", drivetrainBackRight);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainFrontLeft, drivetrainBackLeft,
              drivetrainFrontRight, drivetrainBackRight);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);

        roboRioMainGyro = new AnalogGyro(0);
        LiveWindow.addSensor("RoboRio", "MainGyro", roboRioMainGyro);
        roboRioMainGyro.setSensitivity(0.007);
        roboRioPowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("RoboRio", "PowerDistributionPanel", roboRioPowerDistributionPanel);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
